import './styles.css';
import weatherIcons from './icons';
import { format } from 'date-fns';

//--------------------------------
//     WEATHER API HANDLING
//--------------------------------

async function getWeather(location = 'madrid', unit = 'metric') {
  try {
    const data = await fetch(
      `https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/${location}?unitGroup=${unit}&key=LZSJQYYC6AWFNBWYJETNVFUHM`
    );
    const processedData = await data.json();

    return {
      location: processedData.resolvedAddress.split(',')[0],
      country: processedData.resolvedAddress.split(',').pop().trim(),
      currentConditions: {
        temp: processedData.currentConditions.temp,
        feelsLike: processedData.currentConditions.feelslike,
        conditions: processedData.currentConditions.conditions,
        icon: processedData.currentConditions.icon,
      },
      days: {
        0: {
          dayOfWeek: format(new Date(processedData.days[0].datetime), 'EEEE'),
          date: format(new Date(processedData.days[0].datetime), 'dd MMM'),
          conditions: processedData.days[0].conditions,
          tempMax: Math.floor(processedData.days[0].tempmax),
          tempMin: Math.floor(processedData.days[0].tempmin),
          icon: processedData.days[0].icon,
          hours: processedData.days[0].hours,
        },
        1: {
          dayOfWeek: format(new Date(processedData.days[1].datetime), 'EEEE'),
          date: format(new Date(processedData.days[1].datetime), 'dd MMM'),
          conditions: processedData.days[1].conditions,
          tempMax: Math.floor(processedData.days[1].tempmax),
          tempMin: Math.floor(processedData.days[1].tempmin),
          icon: processedData.days[1].icon,
          hours: processedData.days[1].hours,
        },
        2: {
          dayOfWeek: format(new Date(processedData.days[2].datetime), 'EEEE'),
          date: format(new Date(processedData.days[2].datetime), 'dd MMM'),
          conditions: processedData.days[2].conditions,
          tempMax: Math.floor(processedData.days[2].tempmax),
          tempMin: Math.floor(processedData.days[2].tempmin),
          icon: processedData.days[2].icon,
          hours: processedData.days[2].hours,
        },
        3: {
          dayOfWeek: format(new Date(processedData.days[3].datetime), 'EEEE'),
          date: format(new Date(processedData.days[3].datetime), 'dd MMM'),
          conditions: processedData.days[3].conditions,
          tempMax: Math.floor(processedData.days[3].tempmax),
          tempMin: Math.floor(processedData.days[3].tempmin),
          icon: processedData.days[3].icon,
          hours: processedData.days[3].hours,
        },
      },
    };
  } catch (err) {
    // eslint-disable-next-line no-console
    console.log(err);
    showError();
    return getCity().then(getWeather);
  }
}

//--------------------------------
//        IP API HANDLING
//--------------------------------

async function getCity() {
  const ipData = await fetch('https://ipinfo.io/json?token=d0371dd1f9210d');
  const jsonData = await ipData.json();

  return `${jsonData.city}, ${jsonData.region}, ${jsonData.country}`;
}

//--------------------------------
//        DOM MANIPULATION
//--------------------------------

let unit = 'metric';
let currentLocation;

// Query Selectors
const Selector = (function () {
  return {
    body: document.querySelector('body'),
    unitWrapper: document.getElementById('unit-wrapper'),
    metricSelector: document.getElementById('metric-selector'),
    imperialSelector: document.getElementById('imperial-selector'),
    form: document.querySelector('form'),
    currentBtn: document.getElementById('current-location'),
    location: document.getElementById('location'),
    currentIcon: document.getElementById('current-icon'),
    currentTemp: document.getElementById('current-temp'),
    currentConditions: document.getElementById('current-conditions'),
    currentFeelsLike: document.getElementById('current-feels-like'),
    days: {
      0: {
        icon: document.getElementById('0-icon'),
        temp: document.getElementById('0-temp'),
        conditions: document.getElementById('0-conditions'),
      },
      1: {
        icon: document.getElementById('1-icon'),
        temp: document.getElementById('1-temp'),
        conditions: document.getElementById('1-conditions'),
      },
      2: {
        day: document.getElementById('2-day'),
        icon: document.getElementById('2-icon'),
        temp: document.getElementById('2-temp'),
        conditions: document.getElementById('2-conditions'),
      },
      3: {
        day: document.getElementById('3-day'),
        icon: document.getElementById('3-icon'),
        temp: document.getElementById('3-temp'),
        conditions: document.getElementById('3-conditions'),
      },
    },
  };
})();

// Render the weather on screen
function renderWeather(obj) {
  Selector.body.dataset.style = obj.currentConditions.icon;
  Selector.location.textContent = `${obj.location}, ${obj.country}`;
  Selector.currentIcon.src = weatherIcons[obj.currentConditions.icon];
  if (obj.currentConditions.temp % 1 !== 0) {
    Selector.currentTemp.innerHTML = `${obj.currentConditions.temp.toString().split('.')[0]}<span>.${obj.currentConditions.temp.toString().split('.')[1]}</span>º`;
  } else {
    Selector.currentTemp.textContent = `${obj.currentConditions.temp}º`;
  }
  Selector.currentConditions.textContent = obj.currentConditions.conditions;
  Selector.currentFeelsLike.textContent = `Feels like ${obj.currentConditions.feelsLike}º`;

  renderDay(obj, 0);
  renderDay(obj, 1);
  renderDay(obj, 2);
  renderDay(obj, 3);
}

function renderDay(obj, day) {
  if (day !== 0 && day !== 1)
    Selector.days[day].day.textContent = obj.days[day].dayOfWeek;
  Selector.days[day].icon.src = weatherIcons[obj.days[day].icon];
  Selector.days[day].temp.textContent =
    `${obj.days[day].tempMin}º | ${obj.days[day].tempMax}º`;
  Selector.days[day].conditions.textContent = obj.days[day].conditions;
}

// Render screen during loading
function renderLoading() {
  Selector.location.textContent = '...';
  Selector.currentTemp.textContent = '...';
  Selector.currentConditions.textContent = '...';
  Selector.currentFeelsLike.textContent = '...';

  Selector.days[0].temp.textContent = '...';
  Selector.days[0].conditions.textContent = '...';

  Selector.days[1].temp.textContent = '...';
  Selector.days[1].conditions.textContent = '...';

  Selector.days[2].day.textContent = '...';
  Selector.days[2].temp.textContent = '...';
  Selector.days[2].conditions.textContent = '...';

  Selector.days[3].day.textContent = '...';
  Selector.days[3].temp.textContent = '...';
  Selector.days[3].conditions.textContent = '...';
}

// Change the value of currentLocation
function updateLocation(location) {
  currentLocation = location;
}

// Search form behavior
function searchWeather(e) {
  e.preventDefault();
  if (Selector.form['search-box'].value) {
    renderLoading();
    updateLocation(Selector.form['search-box'].value);
    getWeather(currentLocation, unit).then(renderWeather);
  }
}

// Current location behavior
function searchCurrentLocation() {
  Selector.form.reset();
  renderLoading();
  getCity()
    .then(updateLocation)
    .then(() => getWeather(currentLocation, unit).then(renderWeather));
}

// Unit toggle behavior
function changeUnit(e) {
  const target = e.target.closest('.unit-selector');
  if (
    target === Selector.metricSelector &&
    !Selector.metricSelector.classList.contains('unit-selected')
  ) {
    unit = 'metric';
    Selector.metricSelector.classList.toggle('unit-selected', true);
    Selector.imperialSelector.classList.toggle('unit-selected', false);
    getWeather(currentLocation, unit).then(renderWeather);
  } else if (
    target === Selector.imperialSelector &&
    !Selector.imperialSelector.classList.contains('unit-selected')
  ) {
    unit = 'us';
    Selector.imperialSelector.classList.toggle('unit-selected', true);
    Selector.metricSelector.classList.toggle('unit-selected', false);
    getWeather(currentLocation, unit).then(renderWeather);
  }
}

function showError() {
  const errorMessage = document.createElement('div');
  errorMessage.classList.add('error-message');
  errorMessage.textContent =
    'Oops, we could not find that location. Showing your estimated current location instead';
  Selector.body.appendChild(errorMessage);

  setTimeout(() => {
    errorMessage.classList.add('hidden');
  }, 3000);

  setTimeout(() => {
    errorMessage.remove();
  }, 4000);
}

//--------------------------------
//        EVENT LISTENERS
//--------------------------------

// Selector.form.addEventListener('submit', searchWeather);
// Selector.currentBtn.addEventListener('click', searchCurrentLocation);
// document.addEventListener('DOMContentLoaded', () => {
//   renderLoading();
//   getWeather(currentLocation, unit).then(renderWeather);
// });
// Selector.unitWrapper.addEventListener('click', changeUnit);

const mock = {
  location: 'Madrid',
  country: 'España',
  currentConditions: {
    temp: 18.1,
    feelsLike: 18.1,
    conditions: 'Partially cloudy',
    icon: 'partly-cloudy-day',
  },
  days: {
    0: {
      dayOfWeek: 'Monday',
      date: '12 May',
      conditions: 'Partially cloudy',
      tempMax: 19,
      tempMin: 7,
      icon: 'partly-cloudy-day',
      hours: [
        {
          datetime: '00:00:00',
          datetimeEpoch: 1747000800,
          temp: 11,
          feelslike: 11,
          humidity: 64.66,
          dew: 4.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 17.6,
          windspeed: 8.1,
          winddir: 295,
          pressure: 1015.7,
          visibility: 10,
          cloudcover: 30.6,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO'],
          source: 'obs',
        },
        {
          datetime: '01:00:00',
          datetimeEpoch: 1747004400,
          temp: 9.4,
          feelslike: 7.9,
          humidity: 73.09,
          dew: 4.8,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 14.4,
          windspeed: 10.2,
          winddir: 335,
          pressure: 1015.7,
          visibility: 10,
          cloudcover: 12.2,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-night',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO'],
          source: 'obs',
        },
        {
          datetime: '02:00:00',
          datetimeEpoch: 1747008000,
          temp: 10.1,
          feelslike: 10.1,
          humidity: 70.2,
          dew: 5,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 4.7,
          windspeed: 11.3,
          winddir: 342,
          pressure: 1016,
          visibility: 10,
          cloudcover: 42.4,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO'],
          source: 'obs',
        },
        {
          datetime: '03:00:00',
          datetimeEpoch: 1747011600,
          temp: 8.9,
          feelslike: 7.3,
          humidity: 76.45,
          dew: 5,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 5.4,
          windspeed: 9.8,
          winddir: 329,
          pressure: 1015.7,
          visibility: 10,
          cloudcover: 74.8,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO'],
          source: 'obs',
        },
        {
          datetime: '04:00:00',
          datetimeEpoch: 1747015200,
          temp: 8.8,
          feelslike: 7.4,
          humidity: 75.01,
          dew: 4.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 3.6,
          windspeed: 8.8,
          winddir: 321,
          pressure: 1015,
          visibility: 10,
          cloudcover: 25,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO'],
          source: 'obs',
        },
        {
          datetime: '05:00:00',
          datetimeEpoch: 1747018800,
          temp: 8.5,
          feelslike: 7.9,
          humidity: 78.6,
          dew: 5,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 2.9,
          windspeed: 5.3,
          winddir: 331,
          pressure: 1015,
          visibility: 10,
          cloudcover: 78.9,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO'],
          source: 'obs',
        },
        {
          datetime: '06:00:00',
          datetimeEpoch: 1747022400,
          temp: 7.4,
          feelslike: 6.3,
          humidity: 79.93,
          dew: 4.1,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 3.6,
          windspeed: 6.4,
          winddir: 320,
          pressure: 1015,
          visibility: 10,
          cloudcover: 73.6,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO'],
          source: 'obs',
        },
        {
          datetime: '07:00:00',
          datetimeEpoch: 1747026000,
          temp: 7.6,
          feelslike: 6.9,
          humidity: 81.3,
          dew: 4.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 4,
          windspeed: 5.6,
          winddir: 356,
          pressure: 1015,
          visibility: 10,
          cloudcover: 52.6,
          solarradiation: 1,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO'],
          source: 'obs',
        },
        {
          datetime: '08:00:00',
          datetimeEpoch: 1747029600,
          temp: 8.1,
          feelslike: 8.1,
          humidity: 80.72,
          dew: 5,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 4,
          windspeed: 4,
          winddir: 42,
          pressure: 1015.9,
          visibility: 10,
          cloudcover: 25,
          solarradiation: 51,
          solarenergy: 0.2,
          uvindex: 1,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO', 'LECV'],
          source: 'obs',
        },
        {
          datetime: '09:00:00',
          datetimeEpoch: 1747033200,
          temp: 10.4,
          feelslike: 10.4,
          humidity: 71.52,
          dew: 5.4,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 4.7,
          windspeed: 2.1,
          winddir: 34,
          pressure: 1016,
          visibility: 10,
          cloudcover: 25,
          solarradiation: 228,
          solarenergy: 0.8,
          uvindex: 2,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO', 'LECV'],
          source: 'obs',
        },
        {
          datetime: '10:00:00',
          datetimeEpoch: 1747036800,
          temp: 12,
          feelslike: 12,
          humidity: 66.67,
          dew: 6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 5,
          windspeed: 3.7,
          winddir: 160,
          pressure: 1016,
          visibility: 10,
          cloudcover: 25,
          solarradiation: 505,
          solarenergy: 1.8,
          uvindex: 5,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO', 'LECV'],
          source: 'obs',
        },
        {
          datetime: '11:00:00',
          datetimeEpoch: 1747040400,
          temp: 14,
          feelslike: 14,
          humidity: 57.79,
          dew: 5.8,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 13,
          windspeed: 3.6,
          winddir: 320,
          pressure: 1016,
          visibility: 10,
          cloudcover: 25,
          solarradiation: 710,
          solarenergy: 2.6,
          uvindex: 7,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO', 'LECV'],
          source: 'obs',
        },
        {
          datetime: '12:00:00',
          datetimeEpoch: 1747044000,
          temp: 15.2,
          feelslike: 15.2,
          humidity: 52.59,
          dew: 5.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 25.9,
          windspeed: 8.1,
          winddir: 222,
          pressure: 1016,
          visibility: 10,
          cloudcover: 25,
          solarradiation: 609,
          solarenergy: 2.2,
          uvindex: 6,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO', 'LECV'],
          source: 'obs',
        },
        {
          datetime: '13:00:00',
          datetimeEpoch: 1747047600,
          temp: 16.1,
          feelslike: 16.1,
          humidity: 48.18,
          dew: 5.1,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 25.2,
          windspeed: 10.5,
          winddir: 229,
          pressure: 1015.8,
          visibility: 10,
          cloudcover: 50.1,
          solarradiation: 1059,
          solarenergy: 3.8,
          uvindex: 10,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO', 'LECV'],
          source: 'obs',
        },
        {
          datetime: '14:00:00',
          datetimeEpoch: 1747051200,
          temp: 16.6,
          feelslike: 16.6,
          humidity: 43.69,
          dew: 4.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 33.5,
          windspeed: 15,
          winddir: 212,
          pressure: 1015.7,
          visibility: 10,
          cloudcover: 56.3,
          solarradiation: 735,
          solarenergy: 2.6,
          uvindex: 7,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO', 'LECV'],
          source: 'obs',
        },
        {
          datetime: '15:00:00',
          datetimeEpoch: 1747054800,
          temp: 17.6,
          feelslike: 17.6,
          humidity: 43,
          dew: 4.8,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 40.7,
          windspeed: 12,
          winddir: 202,
          pressure: 1015,
          visibility: 10,
          cloudcover: 57.4,
          solarradiation: 805,
          solarenergy: 2.9,
          uvindex: 8,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO', 'LECV'],
          source: 'obs',
        },
        {
          datetime: '16:00:00',
          datetimeEpoch: 1747058400,
          temp: 18.2,
          feelslike: 18.2,
          humidity: 40.84,
          dew: 4.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 28.4,
          windspeed: 15.2,
          winddir: 207,
          pressure: 1014.1,
          visibility: 10,
          cloudcover: 40.3,
          solarradiation: 708,
          solarenergy: 2.5,
          uvindex: 7,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO', 'LECV'],
          source: 'obs',
        },
        {
          datetime: '17:00:00',
          datetimeEpoch: 1747062000,
          temp: 18.9,
          feelslike: 18.9,
          humidity: 40.2,
          dew: 5,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 42.5,
          windspeed: 11.3,
          winddir: 188,
          pressure: 1013.7,
          visibility: 10,
          cloudcover: 36.3,
          solarradiation: 623,
          solarenergy: 2.2,
          uvindex: 6,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO', 'LECV'],
          source: 'obs',
        },
        {
          datetime: '18:00:00',
          datetimeEpoch: 1747065600,
          temp: 18.3,
          feelslike: 18.3,
          humidity: 41.33,
          dew: 4.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 28.1,
          windspeed: 12.8,
          winddir: 225,
          pressure: 1013.1,
          visibility: 10,
          cloudcover: 39,
          solarradiation: 382,
          solarenergy: 1.4,
          uvindex: 4,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['C1784', 'LEMD', 'LEVS', 'LEGT', 'LETO', 'LECV'],
          source: 'obs',
        },
        {
          datetime: '19:00:00',
          datetimeEpoch: 1747069200,
          temp: 19.1,
          feelslike: 19.1,
          humidity: 31.06,
          dew: 1.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 28.4,
          windspeed: 10.4,
          winddir: 250,
          pressure: 1011,
          visibility: 24.1,
          cloudcover: 58.4,
          solarradiation: 328,
          solarenergy: 1.2,
          uvindex: 3,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '20:00:00',
          datetimeEpoch: 1747072800,
          temp: 18.5,
          feelslike: 18.5,
          humidity: 33.18,
          dew: 2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 26.6,
          windspeed: 9.4,
          winddir: 243.9,
          pressure: 1011,
          visibility: 24.1,
          cloudcover: 55.2,
          solarradiation: 220,
          solarenergy: 0.8,
          uvindex: 2,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '21:00:00',
          datetimeEpoch: 1747076400,
          temp: 17.4,
          feelslike: 17.4,
          humidity: 38.17,
          dew: 3,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 24.5,
          windspeed: 8.3,
          winddir: 249.8,
          pressure: 1012,
          visibility: 24.1,
          cloudcover: 51.3,
          solarradiation: 72,
          solarenergy: 0.3,
          uvindex: 1,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '22:00:00',
          datetimeEpoch: 1747080000,
          temp: 16,
          feelslike: 16,
          humidity: 46.05,
          dew: 4.4,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 19.4,
          windspeed: 5.4,
          winddir: 239.9,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 44.9,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '23:00:00',
          datetimeEpoch: 1747083600,
          temp: 14.8,
          feelslike: 14.8,
          humidity: 49.04,
          dew: 4.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 12.2,
          windspeed: 4.3,
          winddir: 227.8,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 11.6,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-night',
          stations: null,
          source: 'fcst',
        },
      ],
    },
    1: {
      dayOfWeek: 'Tuesday',
      date: '13 May',
      conditions: 'Partially cloudy',
      tempMax: 20,
      tempMin: 9,
      icon: 'partly-cloudy-day',
      hours: [
        {
          datetime: '00:00:00',
          datetimeEpoch: 1747087200,
          temp: 13.8,
          feelslike: 13.8,
          humidity: 53.06,
          dew: 4.4,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 10.1,
          windspeed: 3.6,
          winddir: 243.2,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 0,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '01:00:00',
          datetimeEpoch: 1747090800,
          temp: 12.8,
          feelslike: 12.8,
          humidity: 58.24,
          dew: 4.8,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 7.9,
          windspeed: 3.6,
          winddir: 257.2,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 0,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '02:00:00',
          datetimeEpoch: 1747094400,
          temp: 12.1,
          feelslike: 12.1,
          humidity: 63.57,
          dew: 5.4,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 7.2,
          windspeed: 2.5,
          winddir: 264.5,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 0.7,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '03:00:00',
          datetimeEpoch: 1747098000,
          temp: 11.4,
          feelslike: 11.4,
          humidity: 68.93,
          dew: 5.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 4.7,
          windspeed: 1.8,
          winddir: 286.6,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 20.6,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '04:00:00',
          datetimeEpoch: 1747101600,
          temp: 10.9,
          feelslike: 10.9,
          humidity: 71.75,
          dew: 6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 2.5,
          windspeed: 1.8,
          winddir: 309.6,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 1.8,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '05:00:00',
          datetimeEpoch: 1747105200,
          temp: 10.1,
          feelslike: 10.1,
          humidity: 76.2,
          dew: 6.1,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 2.5,
          windspeed: 1.1,
          winddir: 282.9,
          pressure: 1014,
          visibility: 24.1,
          cloudcover: 4.2,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '06:00:00',
          datetimeEpoch: 1747108800,
          temp: 9.5,
          feelslike: 9.5,
          humidity: 79.33,
          dew: 6.1,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 1.4,
          windspeed: 1.1,
          winddir: 315.4,
          pressure: 1014,
          visibility: 24.1,
          cloudcover: 0,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '07:00:00',
          datetimeEpoch: 1747112400,
          temp: 9,
          feelslike: 9,
          humidity: 82.61,
          dew: 6.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 2.9,
          windspeed: 2.5,
          winddir: 0.1,
          pressure: 1014,
          visibility: 24.1,
          cloudcover: 0,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '08:00:00',
          datetimeEpoch: 1747116000,
          temp: 9.1,
          feelslike: 9.1,
          humidity: 82.63,
          dew: 6.3,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 2.5,
          windspeed: 1.8,
          winddir: 52,
          pressure: 1015,
          visibility: 24.1,
          cloudcover: 0,
          solarradiation: 41,
          solarenergy: 0.1,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '09:00:00',
          datetimeEpoch: 1747119600,
          temp: 11,
          feelslike: 11,
          humidity: 75.83,
          dew: 6.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 5,
          windspeed: 1.4,
          winddir: 76.2,
          pressure: 1015,
          visibility: 24.1,
          cloudcover: 12.5,
          solarradiation: 211,
          solarenergy: 0.8,
          uvindex: 2,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '10:00:00',
          datetimeEpoch: 1747123200,
          temp: 13.3,
          feelslike: 13.3,
          humidity: 63.41,
          dew: 6.5,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 8.3,
          windspeed: 2.2,
          winddir: 123.1,
          pressure: 1015,
          visibility: 24.1,
          cloudcover: 13.6,
          solarradiation: 411,
          solarenergy: 1.5,
          uvindex: 4,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '11:00:00',
          datetimeEpoch: 1747126800,
          temp: 15.4,
          feelslike: 15.4,
          humidity: 56.12,
          dew: 6.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 9.4,
          windspeed: 1.8,
          winddir: 151.3,
          pressure: 1014,
          visibility: 24.1,
          cloudcover: 0.5,
          solarradiation: 603,
          solarenergy: 2.2,
          uvindex: 6,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '12:00:00',
          datetimeEpoch: 1747130400,
          temp: 17,
          feelslike: 17,
          humidity: 50.68,
          dew: 6.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 15.8,
          windspeed: 5,
          winddir: 201.2,
          pressure: 1014,
          visibility: 24.1,
          cloudcover: 53.2,
          solarradiation: 767,
          solarenergy: 2.8,
          uvindex: 8,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '13:00:00',
          datetimeEpoch: 1747134000,
          temp: 18.1,
          feelslike: 18.1,
          humidity: 45.05,
          dew: 6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 19.8,
          windspeed: 6.8,
          winddir: 220.2,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 65.8,
          solarradiation: 888,
          solarenergy: 3.2,
          uvindex: 9,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '14:00:00',
          datetimeEpoch: 1747137600,
          temp: 19,
          feelslike: 19,
          humidity: 41.42,
          dew: 5.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 24.1,
          windspeed: 8.6,
          winddir: 205.6,
          pressure: 1012,
          visibility: 24.1,
          cloudcover: 81.1,
          solarradiation: 958,
          solarenergy: 3.4,
          uvindex: 10,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '15:00:00',
          datetimeEpoch: 1747141200,
          temp: 19.6,
          feelslike: 19.6,
          humidity: 41.02,
          dew: 6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 24.8,
          windspeed: 7.9,
          winddir: 204,
          pressure: 1012,
          visibility: 24.1,
          cloudcover: 75.4,
          solarradiation: 971,
          solarenergy: 3.5,
          uvindex: 10,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '16:00:00',
          datetimeEpoch: 1747144800,
          temp: 20.1,
          feelslike: 20.1,
          humidity: 38.69,
          dew: 5.6,
          precip: 0.1,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 23,
          windspeed: 6.5,
          winddir: 231.7,
          pressure: 1011,
          visibility: 24.1,
          cloudcover: 61.1,
          solarradiation: 924,
          solarenergy: 3.3,
          uvindex: 9,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '17:00:00',
          datetimeEpoch: 1747148400,
          temp: 19.9,
          feelslike: 19.9,
          humidity: 38.1,
          dew: 5.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 23,
          windspeed: 7.6,
          winddir: 227.8,
          pressure: 1011,
          visibility: 24.1,
          cloudcover: 81.8,
          solarradiation: 815,
          solarenergy: 2.9,
          uvindex: 8,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '18:00:00',
          datetimeEpoch: 1747152000,
          temp: 20,
          feelslike: 20,
          humidity: 37.34,
          dew: 5,
          precip: 0.1,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 21.2,
          windspeed: 7.9,
          winddir: 223.3,
          pressure: 1011,
          visibility: 24.1,
          cloudcover: 72.6,
          solarradiation: 523,
          solarenergy: 1.9,
          uvindex: 5,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '19:00:00',
          datetimeEpoch: 1747155600,
          temp: 19.8,
          feelslike: 19.8,
          humidity: 38.07,
          dew: 5.1,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 22.7,
          windspeed: 8.3,
          winddir: 229,
          pressure: 1011,
          visibility: 24.1,
          cloudcover: 32.7,
          solarradiation: 478,
          solarenergy: 1.7,
          uvindex: 5,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '20:00:00',
          datetimeEpoch: 1747159200,
          temp: 19.3,
          feelslike: 19.3,
          humidity: 39.82,
          dew: 5.3,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 22.7,
          windspeed: 8.3,
          winddir: 246.1,
          pressure: 1010,
          visibility: 24.1,
          cloudcover: 5.2,
          solarradiation: 261,
          solarenergy: 0.9,
          uvindex: 3,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '21:00:00',
          datetimeEpoch: 1747162800,
          temp: 18.1,
          feelslike: 18.1,
          humidity: 45.05,
          dew: 6,
          precip: 0,
          precipprob: 9.7,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 21.6,
          windspeed: 8.3,
          winddir: 261.6,
          pressure: 1011,
          visibility: 24.1,
          cloudcover: 15.1,
          solarradiation: 85,
          solarenergy: 0.3,
          uvindex: 1,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '22:00:00',
          datetimeEpoch: 1747166400,
          temp: 16.6,
          feelslike: 16.6,
          humidity: 53.06,
          dew: 7,
          precip: 0,
          precipprob: 9.7,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 20.2,
          windspeed: 5.4,
          winddir: 269.9,
          pressure: 1012,
          visibility: 24.1,
          cloudcover: 98.7,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '23:00:00',
          datetimeEpoch: 1747170000,
          temp: 15.6,
          feelslike: 15.6,
          humidity: 59.33,
          dew: 7.7,
          precip: 0,
          precipprob: 9.7,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 12.2,
          windspeed: 3.6,
          winddir: 251.6,
          pressure: 1012,
          visibility: 24.1,
          cloudcover: 94.3,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
      ],
    },
    2: {
      dayOfWeek: 'Wednesday',
      date: '14 May',
      conditions: 'Rain, Partially cloudy',
      tempMax: 19,
      tempMin: 9,
      icon: 'rain',
      hours: [
        {
          datetime: '00:00:00',
          datetimeEpoch: 1747173600,
          temp: 14.7,
          feelslike: 14.7,
          humidity: 64.16,
          dew: 8,
          precip: 0,
          precipprob: 9.7,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 8.3,
          windspeed: 2.9,
          winddir: 247.1,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 93.8,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '01:00:00',
          datetimeEpoch: 1747177200,
          temp: 14,
          feelslike: 14,
          humidity: 67.14,
          dew: 8,
          precip: 0,
          precipprob: 9.7,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 5.8,
          windspeed: 1.4,
          winddir: 253.2,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 99.1,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '02:00:00',
          datetimeEpoch: 1747180800,
          temp: 13.3,
          feelslike: 13.3,
          humidity: 70.26,
          dew: 8,
          precip: 0,
          precipprob: 9.7,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 3.2,
          windspeed: 1.4,
          winddir: 78,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 32.8,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '03:00:00',
          datetimeEpoch: 1747184400,
          temp: 12.4,
          feelslike: 12.4,
          humidity: 74.53,
          dew: 8,
          precip: 0,
          precipprob: 25.8,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 3.2,
          windspeed: 1.8,
          winddir: 151.1,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 0,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '04:00:00',
          datetimeEpoch: 1747188000,
          temp: 11.6,
          feelslike: 11.6,
          humidity: 79.09,
          dew: 8.1,
          precip: 0,
          precipprob: 25.8,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 2.9,
          windspeed: 0.7,
          winddir: 58.8,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 31.1,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '05:00:00',
          datetimeEpoch: 1747191600,
          temp: 11,
          feelslike: 11,
          humidity: 82.3,
          dew: 8.1,
          precip: 0,
          precipprob: 25.8,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 4,
          windspeed: 2.9,
          winddir: 58.9,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 50.8,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '06:00:00',
          datetimeEpoch: 1747195200,
          temp: 10.2,
          feelslike: 10.2,
          humidity: 87.99,
          dew: 8.3,
          precip: 0,
          precipprob: 25.8,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 5.4,
          windspeed: 2.5,
          winddir: 94.1,
          pressure: 1014,
          visibility: 24.1,
          cloudcover: 33.6,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 3,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '07:00:00',
          datetimeEpoch: 1747198800,
          temp: 9.7,
          feelslike: 9.7,
          humidity: 92.23,
          dew: 8.5,
          precip: 0,
          precipprob: 25.8,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 4.7,
          windspeed: 2.2,
          winddir: 105.8,
          pressure: 1014,
          visibility: 24.1,
          cloudcover: 11.7,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '08:00:00',
          datetimeEpoch: 1747202400,
          temp: 9.8,
          feelslike: 9.8,
          humidity: 93.49,
          dew: 8.8,
          precip: 0,
          precipprob: 25.8,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 4.3,
          windspeed: 1.4,
          winddir: 132.5,
          pressure: 1015,
          visibility: 12.5,
          cloudcover: 22.8,
          solarradiation: 29,
          solarenergy: 0.1,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '09:00:00',
          datetimeEpoch: 1747206000,
          temp: 11.4,
          feelslike: 11.4,
          humidity: 87.51,
          dew: 9.4,
          precip: 0,
          precipprob: 32.3,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 9.4,
          windspeed: 2.9,
          winddir: 137.1,
          pressure: 1015,
          visibility: 24.1,
          cloudcover: 64.7,
          solarradiation: 132,
          solarenergy: 0.5,
          uvindex: 1,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '10:00:00',
          datetimeEpoch: 1747209600,
          temp: 13.4,
          feelslike: 13.4,
          humidity: 77.25,
          dew: 9.5,
          precip: 0,
          precipprob: 32.3,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 19.1,
          windspeed: 6.5,
          winddir: 156.5,
          pressure: 1015,
          visibility: 24.1,
          cloudcover: 74.1,
          solarradiation: 348,
          solarenergy: 1.3,
          uvindex: 3,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '11:00:00',
          datetimeEpoch: 1747213200,
          temp: 15.3,
          feelslike: 15.3,
          humidity: 66.51,
          dew: 9.1,
          precip: 0,
          precipprob: 32.3,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 18.7,
          windspeed: 6.1,
          winddir: 188.1,
          pressure: 1015,
          visibility: 24.1,
          cloudcover: 60.8,
          solarradiation: 568,
          solarenergy: 2,
          uvindex: 6,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '12:00:00',
          datetimeEpoch: 1747216800,
          temp: 16.8,
          feelslike: 16.8,
          humidity: 58.03,
          dew: 8.5,
          precip: 0,
          precipprob: 32.3,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 18.7,
          windspeed: 5.4,
          winddir: 217.3,
          pressure: 1014,
          visibility: 24.1,
          cloudcover: 66.3,
          solarradiation: 758,
          solarenergy: 2.7,
          uvindex: 8,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '13:00:00',
          datetimeEpoch: 1747220400,
          temp: 17.7,
          feelslike: 17.7,
          humidity: 54.45,
          dew: 8.4,
          precip: 0,
          precipprob: 32.3,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 19.8,
          windspeed: 6.1,
          winddir: 249.1,
          pressure: 1014,
          visibility: 24.1,
          cloudcover: 76.2,
          solarradiation: 876,
          solarenergy: 3.2,
          uvindex: 9,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '14:00:00',
          datetimeEpoch: 1747224000,
          temp: 18.5,
          feelslike: 18.5,
          humidity: 53.2,
          dew: 8.8,
          precip: 0.1,
          precipprob: 32.3,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 20.2,
          windspeed: 5.4,
          winddir: 233.3,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 57.5,
          solarradiation: 946,
          solarenergy: 3.4,
          uvindex: 9,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '15:00:00',
          datetimeEpoch: 1747227600,
          temp: 19.6,
          feelslike: 19.6,
          humidity: 50.01,
          dew: 8.9,
          precip: 0,
          precipprob: 32.3,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 20.2,
          windspeed: 5.4,
          winddir: 233.1,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 89.7,
          solarradiation: 958,
          solarenergy: 3.4,
          uvindex: 10,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '16:00:00',
          datetimeEpoch: 1747231200,
          temp: 18.8,
          feelslike: 18.8,
          humidity: 53.64,
          dew: 9.2,
          precip: 0.1,
          precipprob: 32.3,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 24.5,
          windspeed: 8.3,
          winddir: 257.3,
          pressure: 1013,
          visibility: 14,
          cloudcover: 92.7,
          solarradiation: 627,
          solarenergy: 2.3,
          uvindex: 6,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '17:00:00',
          datetimeEpoch: 1747234800,
          temp: 19.7,
          feelslike: 19.7,
          humidity: 45.19,
          dew: 7.5,
          precip: 0,
          precipprob: 32.3,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 23,
          windspeed: 6.8,
          winddir: 257,
          pressure: 1012,
          visibility: 24.1,
          cloudcover: 57.4,
          solarradiation: 184,
          solarenergy: 0.7,
          uvindex: 2,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '18:00:00',
          datetimeEpoch: 1747238400,
          temp: 19.8,
          feelslike: 19.8,
          humidity: 43.4,
          dew: 7,
          precip: 0.1,
          precipprob: 32.3,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 27,
          windspeed: 9.4,
          winddir: 242.2,
          pressure: 1012,
          visibility: 24.1,
          cloudcover: 69.5,
          solarradiation: 74,
          solarenergy: 0.3,
          uvindex: 1,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '19:00:00',
          datetimeEpoch: 1747242000,
          temp: 17.8,
          feelslike: 17.8,
          humidity: 56.35,
          dew: 9,
          precip: 0.1,
          precipprob: 32.3,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 29.5,
          windspeed: 9.7,
          winddir: 272.3,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 127,
          solarenergy: 0.5,
          uvindex: 1,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '20:00:00',
          datetimeEpoch: 1747245600,
          temp: 16.8,
          feelslike: 16.8,
          humidity: 62.5,
          dew: 9.6,
          precip: 0.3,
          precipprob: 32.3,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 24.8,
          windspeed: 4.7,
          winddir: 16.5,
          pressure: 1013,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 245,
          solarenergy: 0.9,
          uvindex: 2,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '21:00:00',
          datetimeEpoch: 1747249200,
          temp: 14.9,
          feelslike: 14.9,
          humidity: 75.96,
          dew: 10.7,
          precip: 0.6,
          precipprob: 61.3,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 24.1,
          windspeed: 6.8,
          winddir: 96,
          pressure: 1014,
          visibility: 13.1,
          cloudcover: 100,
          solarradiation: 34,
          solarenergy: 0.1,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '22:00:00',
          datetimeEpoch: 1747252800,
          temp: 13.9,
          feelslike: 13.9,
          humidity: 85.45,
          dew: 11.5,
          precip: 0.1,
          precipprob: 61.3,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 18.4,
          windspeed: 3.6,
          winddir: 62.4,
          pressure: 1015,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '23:00:00',
          datetimeEpoch: 1747256400,
          temp: 13.5,
          feelslike: 13.5,
          humidity: 86.55,
          dew: 11.3,
          precip: 0.4,
          precipprob: 61.3,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 9.4,
          windspeed: 0.7,
          winddir: 255.9,
          pressure: 1016,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
      ],
    },
    3: {
      dayOfWeek: 'Thursday',
      date: '15 May',
      conditions: 'Rain, Partially cloudy',
      tempMax: 19,
      tempMin: 11,
      icon: 'rain',
      hours: [
        {
          datetime: '00:00:00',
          datetimeEpoch: 1747260000,
          temp: 12.9,
          feelslike: 12.9,
          humidity: 88.82,
          dew: 11.1,
          precip: 0.9,
          precipprob: 61.3,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 5,
          windspeed: 1.8,
          winddir: 322.5,
          pressure: 1016,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '01:00:00',
          datetimeEpoch: 1747263600,
          temp: 12.7,
          feelslike: 12.7,
          humidity: 88.8,
          dew: 10.9,
          precip: 0.3,
          precipprob: 61.3,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 6.1,
          windspeed: 0.7,
          winddir: 302.8,
          pressure: 1015,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '02:00:00',
          datetimeEpoch: 1747267200,
          temp: 12.4,
          feelslike: 12.4,
          humidity: 89.97,
          dew: 10.8,
          precip: 0,
          precipprob: 61.3,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 5,
          windspeed: 2.2,
          winddir: 321.1,
          pressure: 1015,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '03:00:00',
          datetimeEpoch: 1747270800,
          temp: 12.1,
          feelslike: 12.1,
          humidity: 91.15,
          dew: 10.7,
          precip: 0,
          precipprob: 45.2,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 4.7,
          windspeed: 0.7,
          winddir: 323.7,
          pressure: 1015,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '04:00:00',
          datetimeEpoch: 1747274400,
          temp: 11.8,
          feelslike: 11.8,
          humidity: 91.74,
          dew: 10.5,
          precip: 0.2,
          precipprob: 45.2,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 2.9,
          windspeed: 1.8,
          winddir: 320.4,
          pressure: 1016,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '05:00:00',
          datetimeEpoch: 1747278000,
          temp: 11.5,
          feelslike: 11.5,
          humidity: 92.34,
          dew: 10.3,
          precip: 1,
          precipprob: 45.2,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 5,
          windspeed: 2.2,
          winddir: 315.8,
          pressure: 1016,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '06:00:00',
          datetimeEpoch: 1747281600,
          temp: 11.5,
          feelslike: 11.5,
          humidity: 92.34,
          dew: 10.3,
          precip: 1.2,
          precipprob: 45.2,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 5.8,
          windspeed: 2.5,
          winddir: 316.9,
          pressure: 1016,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '07:00:00',
          datetimeEpoch: 1747285200,
          temp: 11.4,
          feelslike: 11.4,
          humidity: 92.33,
          dew: 10.2,
          precip: 0.5,
          precipprob: 45.2,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 7.2,
          windspeed: 3.2,
          winddir: 308.8,
          pressure: 1016,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '08:00:00',
          datetimeEpoch: 1747288800,
          temp: 11.7,
          feelslike: 11.7,
          humidity: 90.52,
          dew: 10.2,
          precip: 0,
          precipprob: 45.2,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 8.3,
          windspeed: 3.6,
          winddir: 321,
          pressure: 1017,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 30,
          solarenergy: 0.1,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '09:00:00',
          datetimeEpoch: 1747292400,
          temp: 12.5,
          feelslike: 12.5,
          humidity: 82.49,
          dew: 9.6,
          precip: 0,
          precipprob: 58.1,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 11.2,
          windspeed: 4,
          winddir: 347.7,
          pressure: 1017,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 112,
          solarenergy: 0.4,
          uvindex: 1,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '10:00:00',
          datetimeEpoch: 1747296000,
          temp: 14.2,
          feelslike: 14.2,
          humidity: 71.88,
          dew: 9.2,
          precip: 0,
          precipprob: 58.1,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 15.8,
          windspeed: 5.8,
          winddir: 6.2,
          pressure: 1017,
          visibility: 24.1,
          cloudcover: 83.5,
          solarradiation: 171,
          solarenergy: 0.6,
          uvindex: 2,
          severerisk: 10,
          conditions: 'Rain, Partially cloudy',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '11:00:00',
          datetimeEpoch: 1747299600,
          temp: 16,
          feelslike: 16,
          humidity: 61.06,
          dew: 8.5,
          precip: 0,
          precipprob: 58.1,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 27.7,
          windspeed: 10.8,
          winddir: 37.8,
          pressure: 1017,
          visibility: 22.9,
          cloudcover: 80.1,
          solarradiation: 108,
          solarenergy: 0.4,
          uvindex: 1,
          severerisk: 10,
          conditions: 'Rain, Partially cloudy',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '12:00:00',
          datetimeEpoch: 1747303200,
          temp: 16.9,
          feelslike: 16.9,
          humidity: 58.85,
          dew: 8.8,
          precip: 0,
          precipprob: 58.1,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 32.8,
          windspeed: 11.2,
          winddir: 49.5,
          pressure: 1017,
          visibility: 24.1,
          cloudcover: 68.9,
          solarradiation: 108,
          solarenergy: 0.4,
          uvindex: 1,
          severerisk: 10,
          conditions: 'Rain, Partially cloudy',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '13:00:00',
          datetimeEpoch: 1747306800,
          temp: 18.1,
          feelslike: 18.1,
          humidity: 55.67,
          dew: 9.1,
          precip: 0.1,
          precipprob: 58.1,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 34.9,
          windspeed: 10.8,
          winddir: 58.7,
          pressure: 1017,
          visibility: 22.9,
          cloudcover: 58.4,
          solarradiation: 177,
          solarenergy: 0.6,
          uvindex: 2,
          severerisk: 10,
          conditions: 'Rain, Partially cloudy',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '14:00:00',
          datetimeEpoch: 1747310400,
          temp: 19,
          feelslike: 19,
          humidity: 50.19,
          dew: 8.4,
          precip: 0.1,
          precipprob: 58.1,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 35.6,
          windspeed: 8.6,
          winddir: 50.7,
          pressure: 1017,
          visibility: 24.1,
          cloudcover: 70.1,
          solarradiation: 251,
          solarenergy: 0.9,
          uvindex: 3,
          severerisk: 10,
          conditions: 'Rain, Partially cloudy',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '15:00:00',
          datetimeEpoch: 1747314000,
          temp: 19.1,
          feelslike: 19.1,
          humidity: 51.37,
          dew: 8.8,
          precip: 0,
          precipprob: 58.1,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 34.1,
          windspeed: 8.5,
          winddir: 53,
          pressure: 1016.7,
          visibility: 24.1,
          cloudcover: 68.3,
          solarradiation: 328,
          solarenergy: 1.2,
          uvindex: 3,
          severerisk: 10,
          conditions: 'Rain, Partially cloudy',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '16:00:00',
          datetimeEpoch: 1747317600,
          temp: 19.2,
          feelslike: 19.2,
          humidity: 52.57,
          dew: 9.3,
          precip: 0,
          precipprob: 58.1,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 32.5,
          windspeed: 8.4,
          winddir: 55.3,
          pressure: 1016.3,
          visibility: 24.1,
          cloudcover: 66.5,
          solarradiation: 375,
          solarenergy: 1.3,
          uvindex: 4,
          severerisk: 10,
          conditions: 'Rain, Partially cloudy',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '17:00:00',
          datetimeEpoch: 1747321200,
          temp: 19.4,
          feelslike: 19.4,
          humidity: 53.8,
          dew: 9.8,
          precip: 0.6,
          precipprob: 58.1,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 31,
          windspeed: 8.3,
          winddir: 57.6,
          pressure: 1016,
          visibility: 24.1,
          cloudcover: 64.7,
          solarradiation: 380,
          solarenergy: 1.4,
          uvindex: 4,
          severerisk: 10,
          conditions: 'Rain, Partially cloudy',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '18:00:00',
          datetimeEpoch: 1747324800,
          temp: 18.5,
          feelslike: 18.5,
          humidity: 59.51,
          dew: 10.4,
          precip: 0,
          precipprob: 58.1,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 29.5,
          windspeed: 8,
          winddir: 157.4,
          pressure: 1016.3,
          visibility: 24.1,
          cloudcover: 76.5,
          solarradiation: 437,
          solarenergy: 1.6,
          uvindex: 4,
          severerisk: 10,
          conditions: 'Rain, Partially cloudy',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '19:00:00',
          datetimeEpoch: 1747328400,
          temp: 17.6,
          feelslike: 17.6,
          humidity: 65.83,
          dew: 11.2,
          precip: 0,
          precipprob: 58.1,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 28.1,
          windspeed: 7.8,
          winddir: 257.3,
          pressure: 1016.7,
          visibility: 24.1,
          cloudcover: 88.2,
          solarradiation: 362,
          solarenergy: 1.3,
          uvindex: 4,
          severerisk: 10,
          conditions: 'Rain, Partially cloudy',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '20:00:00',
          datetimeEpoch: 1747332000,
          temp: 16.8,
          feelslike: 16.8,
          humidity: 72.83,
          dew: 11.9,
          precip: 1.2,
          precipprob: 58.1,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 26.6,
          windspeed: 7.6,
          winddir: 357.1,
          pressure: 1017,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 120,
          solarenergy: 0.4,
          uvindex: 1,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '21:00:00',
          datetimeEpoch: 1747335600,
          temp: 16.3,
          feelslike: 16.3,
          humidity: 75.02,
          dew: 11.8,
          precip: 0,
          precipprob: 22.6,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 20.2,
          windspeed: 6.1,
          winddir: 354.8,
          pressure: 1017.3,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 37,
          solarenergy: 0.1,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '22:00:00',
          datetimeEpoch: 1747339200,
          temp: 15.8,
          feelslike: 15.8,
          humidity: 77.29,
          dew: 11.8,
          precip: 0,
          precipprob: 22.6,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 13.7,
          windspeed: 4.7,
          winddir: 352.6,
          pressure: 1017.7,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '23:00:00',
          datetimeEpoch: 1747342800,
          temp: 15.3,
          feelslike: 15.3,
          humidity: 79.63,
          dew: 11.8,
          precip: 0,
          precipprob: 22.6,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 7.2,
          windspeed: 3.2,
          winddir: 350.3,
          pressure: 1018,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
      ],
    },
  },
};

renderWeather(mock);